import React from "react";

import StyledComponentsRegistry from "./lib/registry";

import "./globals.css";
import { ConfigProvider } from "antd";
import theme from "../../theme/themeConfig";
import Header from "@/layouts/Header";

import { Outfit,Montserrat } from "next/font/google";
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: '--font-outfit',
});
export const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en" className={`${outfit.variable} ${montserrat.variable}`}>
    <body>
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
          <div className="mx-auto max-w-[1428px]">
            <Header />
            {children}
          </div>
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
